---
title: "Explore osmar package for extracting trails"
author: "Marc Weber"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: yeti
    highlighted: default
    toc: yes
    toc_float: true
---

### Try extracting trails around Jackson Frazier
```{r warning=FALSE, error=FALSE, message=FALSE}
library(osmar)
library(sf)
src <- osmsource_api()
counties <- st_read('C:/Users/mweber/Temp/Counties.shp')
benton <- subset(counties, NAME=='Benton' & STATE_NAME=='Oregon')
st_bbox(benton)
bb <- corner_bbox(-123.259, 44.598, -123.228, 44.617)
osm_jf <- get_osm(bb, source = src)
plot(osm_jf, xlim=c(-123.6, -123.1))
names(osm_jf)
summary(osm_jf$ways)
summary(osm_jf$ways$tags)
trails <- find(osm_jf, way(tags(k == "highway" & (v == "footway" | v == "path"))))
trails <- find_down(osm_jf, way(trails))
trails <- subset(osm_jf, ids = trails)
plot(trails)
```

### Convert to spatial, then simple features, and make an interactive slippy map
```{r warning=FALSE, error=FALSE, message=FALSE}
library(sf)
library(mapview)
# convert to sp
trails <- as_sp(trails, "lines")
# convert to sf
trails <- st_as_sf(trails)
mapview(trails$geometry)
```

### Hypothetical 1km buffer located in Jackson Frazier Wetland
```{r warning=FALSE, error=FALSE, message=FALSE}
site <- data.frame(place=c("Jackson Frazier"),longitude=c(-123.24),latitude=c(44.60))
coordinates(site) <- ~ longitude + latitude
proj4string(site) <- '+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs'
site <- st_as_sf(site)
# transform to planar (UTM 10N) in order to create buffer
site <- st_transform(site, crs=3157)
buf_1k <- st_buffer(site, 1000)

# transform trails to same CRS
trails <- st_transform(trails, crs=3157)

# plot together
mapview(list(trails$geometry,buf_1k))
```

### Now we can calculate trail density in 1km buffer around wetland
```{r warning=FALSE, error=FALSE, message=FALSE}
trails_in_buf <- st_intersection(buf_1k, trails)
length <- st_length(trails_in_buf)
length <- sum(length)
print(paste0('Trail Density: ',length[[1]], 'meters per sq. km' ))

```